# Generated by Django 2.2.4 on 2020-01-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(max_length=200)),
                ('model_id', models.IntegerField()),
                ('data', models.TextField()),
            ],
        ),
    ]
