# Generated by Django 2.2.4 on 2020-02-11 14:39

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_deleteddata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='start',
            field=models.DateField(default=api.models.now),
        ),
    ]
